CREATE TABLE Meniu(
	Id INT PRIMARY KEY NOT NULL,
	Nume VARCHAR(50)
);

CREATE TABLE DetaliiMeniu(
	Id INT,
	Tip VARCHAR(50) PRIMARY KEY,
	Pret FLOAT,
	Ingrediente VARCHAR(50)
);

ALTER TABLE DetaliiMeniu
ADD CONSTRAINT FK_Id
FOREIGN KEY (Id) REFERENCES Meniu(Id);